### ISSUE TITLE
开题报告名称改成博士学位开题报告如何修改？

### ISSUE THREAD

**Issue by Admin-OF-Admin** [blknaoh/zjuthesis-OCproposal#2]
你好啊！我想请问一下这个开题报告标题如何修改成博士学位的呢？\TitleTypeNameCover 是不是修改这个呢 但我没有找到他 不知道在哪里修改，感谢提供模板！

**Comment by Admin-OF-Admin** [comment]
不好意思 我没仔细看 gradlevel里面改成博士就好了 可以忽略这个

**Comment by blknaoh** [comment]
好的，祝开题顺利！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月17日 10:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [blknaoh/zjuthesis-OCproposal] 开题报告名称改成博士学位开题报告如何修改？ (Issue #2) |

不好意思 我没仔细看 gradlevel里面改成博士就好了 可以忽略这个
